name: "e2e-couchdb"
on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - opened
jobs:
  e2e-couchdb:
    if: ${{ github.event.label.name == 'pr:e2e:couchdb' }} || ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/gallium'
      - run: npx playwright@1.32.3 install
      - run: npm install
      - name: Start CouchDB Docker Container and Init with Setup Scripts
        run : |
          export $(cat src/plugins/persistence/couch/.env.ci | xargs)
          docker-compose -f src/plugins/persistence/couch/couchdb-compose.yaml up --detach
          sleep 3
          bash src/plugins/persistence/couch/setup-couchdb.sh
          bash src/plugins/persistence/couch/replace-localstorage-with-couchdb-indexhtml.sh
      - name: Run CouchDB Tests and publish to deploysentinel
        env:
          DEPLOYSENTINEL_API_KEY: ${{ secrets.DEPLOYSENTINEL_API_KEY }} 
        run: npm run test:e2e:couchdb
      - name: Publish Results to Codecov.io
        env: 
          SUPER_SECRET: ${{ secrets.CODECOV_TOKEN }}
        run: npm run cov:e2e:full:publish
      - name: Archive test results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          path: test-results
      - name: Archive html test results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          path: html-test-results
      - name: Remove pr:e2e:couchdb label (if present)
        if: ${{ contains(github.event.pull_request.labels.*.name, 'pr:e2e:couchdb') }}
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const labelToRemove = 'pr:e2e:couchdb';
            await github.rest.issues.removeLabel({
              owner,
              repo,
              issue_number: number,
              name: labelToRemove
            });
